### ISSUE TITLE
1.21 fabric crashes on startup presumably because of "No data fixer registered for bullet_entity"

### ISSUE THREAD

**Issue by Ynaught** [BrokenK3yboard/SimpleMusket#10]
Not sure what that means but that's the last thing in the log before the crash.

The crash report didn't tell me anything but here ya go:

> ---- Minecraft Crash Report ----
> // On the bright side, I bought you a teddy bear!
> 
> Time: 2024-06-25 23:48:09
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'cardinal-components-entity'!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at net.minecraft.class_310.<init>(class_310.java:477)
> 	at net.minecraft.client.main.Main.main(Main.java:239)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: org.ladysnake.cca.internal.base.asm.StaticComponentLoadingException: Exception while registering static component factories for Dyed Item Frames (dyed_item_frames)
> 	at org.ladysnake.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:171)
> 	at org.ladysnake.cca.internal.entity.StaticEntityComponentPlugin.init(StaticEntityComponentPlugin.java:105)
> 	at org.ladysnake.cca.internal.base.LazyDispatcher.ensureInitialized(LazyDispatcher.java:46)
> 	at org.ladysnake.cca.internal.entity.CardinalComponentsEntity.init(CardinalComponentsEntity.java:106)
> 	at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199)
> 	at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy44.onInitialize(Unknown Source)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
> 	... 6 more
> Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'cardinal-components-entity' provided by 'dyed_item_frames'
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
> 	at org.ladysnake.cca.internal.base.asm.StaticComponentPluginBase.processInitializers(StaticComponentPluginBase.java:168)
> 	... 12 more
> Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class com.boyonk.dyeditemframes.DyedItemFrames cannot be cast to org.ladysnake.cca.api.v3.entity.EntityComponentInitializer!
> 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:63)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
> 	... 13 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at net.minecraft.class_310.<init>(class_310.java:477)
> 
> -- Initialization --
> Details:
> 	Modules: 
> 		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
> 		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		DBGHELP.DLL:Windows Image Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		GDI32.dll:GDI Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
> 		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
> 		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		MpOav.dll:IOfficeAntiVirus Module:4.18.24050.7 (b60bcb9c79f050335eb91db16f7d3e97336ad10e-dirty):Microsoft Corporation
> 		NLAapi.dll:Network Location Awareness 2:10.0.19041.4123 (WinBuild.160101.0800):Microsoft Corporation
> 		NSI.dll:NSI User-mode interface DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		Ole32.dll:Microsoft OLE for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		POWRPROF.dll:Power Profile Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		PSAPI.DLL:Process Status Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		SHELL32.dll:Windows Shell Common Dll:10.0.19041.4123 (WinBuild.160101.0800):Microsoft Corporation
> 		UMPDC.dll
> 		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
> 		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		WINHTTP.dll:Windows HTTP Services:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		amsi.dll:Anti-Malware Scan Interface:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
> 		apphelp.dll:Application Compatibility Client Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		awt.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
> 		combase.dll:Microsoft COM for Windows:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
> 		extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		gdi32full.dll:GDI Client DLL:10.0.19041.4474 (WinBuild.160101.0800):Microsoft Corporation
> 		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
> 		java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		javaw.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		jemalloc.dll
> 		jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		jna10225895911905964495.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
> 		jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
> 		kernel.appcore.dll:AppModel API Host:10.0.19041.3758 (WinBuild.160101.0800):Microsoft Corporation
> 		lwjgl.dll
> 		management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		mdnsNSP.dll:Bonjour Namespace Provider:3,1,0,1:Apple Inc.
> 		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
> 		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		msvcrt.dll:Windows NT CRT DLL:7.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		ntdll.dll:NT Layer DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		profapi.dll:User Profile Basic API:10.0.19041.4355 (WinBuild.160101.0800):Microsoft Corporation
> 		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		sunmscapi.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
> 		verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> 		win32u.dll:Win32u:10.0.19041.4529 (WinBuild.160101.0800):Microsoft Corporation
> 		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
> 		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.3636 (WinBuild.160101.0800):Microsoft Corporation
> 		zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(Main.java:239)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> 	Launched Version: 1.21
> 	Launcher name: ATLauncher
> 	Backend library: LWJGL version 3.3.3-snapshot
> 	Backend API: Unknown
> 	Window size: <not initialized>
> 	GFLW Platform: <error>
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: <disabled>
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Universe: 404
> 	Type: Client (map_client.txt)
> 	Locale: en_US
> 	System encoding: Cp1252
> 	File encoding: UTF-8
> 	CPU: <unknown>

**Comment by Ynaught** [comment]
Nvm, seems like dyed item frames was the cause of the crash. Guess I'll move this over to them then.
